2025-05-10 08:47:32.569958: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-10 08:47:32.573086: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-10 08:47:32.581502: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1746866852.595749    2196 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1746866852.600018    2196 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1746866852.611723    2196 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746866852.611748    2196 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746866852.611751    2196 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746866852.611753    2196 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-10 08:47:32.615271: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
YF.download() has changed argument auto_adjust default to True
Data kosong atau kolom hilang untuk AKRA.JK
Data kosong atau kolom hilang untuk AKRA.JK
Data kosong atau kolom hilang untuk AKRA.JK
Gagal download data untuk AKRA.JK: No objects to concatenate
Data kosong atau kolom hilang untuk MNCN.JK
Data kosong atau kolom hilang untuk MNCN.JK
Data kosong atau kolom hilang untuk MNCN.JK
Data kosong atau kolom hilang untuk MNCN.JK
Data kosong atau kolom hilang untuk AKRA.JK
Data kosong atau kolom hilang untuk MNCN.JK
Traceback (most recent call last):
  File "/home/runner/work/Whatman42/Whatman42/main.py", line 1701, in <module>
    results = list(executor.map(analyze_stock, STOCK_LIST))
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/work/Whatman42/Whatman42/main.py", line 912, in analyze_stock
    check_and_reset_model_if_needed(ticker, features)
  File "/home/runner/work/Whatman42/Whatman42/main.py", line 1526, in check_and_reset_model_if_needed
    akurasi_map = evaluate_prediction_accuracy()
  File "/home/runner/work/Whatman42/Whatman42/main.py", line 1216, in evaluate_prediction_accuracy
    df_data = get_realized_price_data()
  File "/home/runner/work/Whatman42/Whatman42/main.py", line 1196, in get_realized_price_data
    "actual_high": pd.to_numeric(df_window["High"], errors="coerce").max(),
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/pandas/core/tools/numeric.py", line 206, in to_numeric
    raise TypeError("arg must be a list, tuple, 1-d array, or Series")
TypeError: arg must be a list, tuple, 1-d array, or Series
